image: node:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - lint
  - build
  - test

install:
  stage: install
  script: 
    - npm install

lint:
  stage: lint
  script:
   - npm run lint

build:
  stage: build
  script: 
    - npm run build

test:
  stage: test
  script:
   - npm run test