image: node:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - lint
  - build
  - test
  - pages

install:
  stage: install
  script: 
    - npm ci

lint:
  stage: lint
  script:
   - npm run lint

build:
  stage: build
  script: 
    - npm run build

test:
  stage: test
  script:
   - npm run test
  artifacts:
    paths:
      - coverage/

pages:
  stage: pages
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master