# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

cache:
  paths:
  - node_modules/

stages:
  - install
  - lint
  - build
  - test

install:
  stage: install
  script: 
    - npm ci

lint:
  stage: lint
  script:
   - npm run lint

build:
  stage: build
  script: 
    - npm run build

test:
  stage: test
  script:
   - npm run test
